### ISSUE TITLE
How to include csproj in VisualStudio

### ISSUE THREAD

**Issue by amerkoleci** [novelrt/NovelRT#309] opened 2021-05-11 08:55 UTC
Hi,

I was trying to build the framework and would like to know how can I edit cs files in Visual Studio when building with CMake?

I know CMake supports: include_external_msproject which is not used.

Thanks

**Comment by amerkoleci** [comment] 2021-05-11 09:09
include_external_msproject  works with new csproj as well, I was adding .net5 support in my C++ game engine and ended here, will keep monitored :)

**Comment by RubyNova** [comment] 2021-05-11 09:12
![image](https://user-images.githubusercontent.com/25829582/117790400-382ca380-b241-11eb-9fec-5a4e2ed9e468.png)

For context, the problem is here. It does nothing on UNIX-based systems, which we support. This is our main reason for not using it, as the last time we checked into it, it only functioned with Framework. CMake is honestly really inconsistent and sometimes I wish it would just....not be.

**Closed** 2021-10-05 17:00 UTC
